### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by iwubcode** [NiV-L-A/Endless-Ocean-Files-Converter#1]
Thank you for working on this!

Another developer and I work on [a tool](https://github.com/Venomalia/DolphinTextureExtraction-tool) with the goal of being able to parse as many Wii/GC game formats as possible and dump the textures.  Some of the formats are reversed by us but others we leverage from the community (with credit).  I'd love to leverage the formats you've reversed engineered in that tool and possibly reuse some of the code (if applicable).

I'm curious what the license is for this converter?

**Comment by NiV-L-A** [comment]
Hi, thanks!
This converter uses the GNU General Public License v3.0, so you're free to use the code as long as you credit the original source.
I will push soon another version which includes, among some fixes, the LICENSE file.
I recommend checking out the python script that I wrote. That code is structured much better ( https://github.com/NiV-L-A/fmt_endlessocean_mdl ).
I will also upload my 010 Editor Binary Template file of the Endless Ocean .mdl structure soon...somewhere!

**Comment by NiV-L-A** [comment]
I pushed a new version (1.7.6).
From now on this repository has a LICENSE file.
